default_setup_params: &default_setup_params
    no_batching: false
    use_viewdirs: false
    N_rand: 1024
    device: 'cuda'
    i_weights: 50000
    i_testset: 1500
    i_video: 100000
    i_print: 50000
    input_dims_embed: 3
    white_bkgd: True
    half_res: true
    chunk: 16384
    netchunk: 16384
    testskip: 80


default_flame_nerf_params: &default_flame_nerf_params
  epsilon: 0.006
  fake_epsilon: 0.04
  trans_the_smallest_epsilon: 0.15
  trans_the_biggest_epsilon: 0.005
  n_the_farthest_samples: 50
  n_central_samples: 10
  n_additional_samples: 2
  chunk_render: 1024


default_flame_setup_params: &default_flame_setup_params
  flame_model_path: './FLAME/model/generic_model.pkl'

default_nerf_setup_params: &default_nerf_setup_params
    N_samples: 110
    N_importance: 300

dataset_face_m1047S_setup: &dataset_face_m1047S_setup
    basedir: "logs"
    datadir: "data/face_m1047_S"
    dataset_type: "blender"
    near: 3.0
    far: 5.5

face_m1047S_flame_nerf:
  module: "flame_nerf.FlameTrainer"
  kwargs:
    <<: *default_setup_params
    <<: *default_nerf_setup_params
    <<: *default_flame_nerf_params
    <<: *dataset_face_m1047S_setup
    expname: "m1047S_enhanced_mode_true_start_after_1_eps_0_006_lr_0_001"
    flame_config:
      module: "FLAME.FlameConfig"
      kwargs:
        <<: *default_flame_setup_params
